Repository abhaykatheria/cp, pull requests merged in 2020-10, with the labels that each got.

#5 binary tree conepts
  Tree Concepts/BIT.cpp
  Tree Concepts/binary_search_tree.cpp
  Tree Concepts/burn_tree.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#7 added Educational Codeforces Round 96
  cf contests/Educational Codeforces Round 96 (Rated for Div. 2)/A.cpp
  cf contests/Educational Codeforces Round 96 (Rated for Div. 2)/B.cpp
  cf contests/Educational Codeforces Round 96 (Rated for Div. 2)/C.cpp
  cf contests/Educational Codeforces Round 96 (Rated for Div. 2)/D.cpp
  cf contests/Educational Codeforces Round 96 (Rated for Div. 2)/E.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#8 added cf round #667 (Div. 3)
  cf contests/Codeforces Round #667 (Div. 3)/A.cpp
  cf contests/Codeforces Round #667 (Div. 3)/B.cpp
  cf contests/Codeforces Round #667 (Div. 3)/C.cpp
  cf contests/Codeforces Round #667 (Div. 3)/D.cpp
  cf contests/Codeforces Round #667 (Div. 3)/E.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 added codechef contests
  September Lunchtime 2020 Division 2/GCDOPS.cpp
  September Lunchtime 2020 Division 2/PERMSPL.cpp
  September Lunchtime 2020 Division 2/ROOTTREE.cpp
  September Lunchtime 2020 Division 2/WATMELON.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#14 Coding Blocks
  CodingBlocks/AsciiDiff.py
  CodingBlocks/BiggestNum.py
  CodingBlocks/COunt.py
  CodingBlocks/CanYouReadThis.py
  CodingBlocks/Change Case.py
  CodingBlocks/Check Prime.py
  CodingBlocks/Combo.py
  CodingBlocks/Delhi Odd Even.py
  CodingBlocks/Frequency.py
  CodingBlocks/Input_Output.py
  CodingBlocks/Maximum Occurence.py
  CodingBlocks/Mountain.py
  CodingBlocks/Numbers & Stars-1.py
  CodingBlocks/Numbers & Stars-2.py
  CodingBlocks/Park.py
  CodingBlocks/Pattern 0.py
  CodingBlocks/PrateekAnd MAths.py
  CodingBlocks/Primes.py
  CodingBlocks/Pythagorian Triplets.py
  CodingBlocks/Quadratic.py
  CodingBlocks/Sieve.py
  CodingBlocks/Sorted Strings.py
  CodingBlocks/Sorted.py
  CodingBlocks/Square.py
  CodingBlocks/SumofArrays.py
  CodingBlocks/Tdaas.py
  CodingBlocks/Triplets.py
  CodingBlocks/Unique Number III.py
  CodingBlocks/combo 2.py
  CodingBlocks/redmi.py
  CodingBlocks/subSeq.py
  CodingBlocks/swapswap.py
Labels: hacktoberfest, hacktoberfest-accepted

#15 added cf contest
  Codeforces Round #661 (Div. 3)/A.cpp
  Codeforces Round #661 (Div. 3)/B.cpp
  Codeforces Round #661 (Div. 3)/C.cpp
  Codeforces Round #661 (Div. 3)/D.cpp
  firstcommifile.txt
Labels: hacktoberfest, hacktoberfest-accepted

#16 graph concepts
  arrays/kth_lar_ele_in_stream.cpp
  arrays/max_sum_key.cpp
  arrays/min_in_rotated_sorted.cpp
  graph/articulation_point.cpp
  graph/dijkstra_adjM.cpp
  graph/kruskal.cpp
  graph/strongly_connected.cpp
Labels: hacktoberfest, hacktoberfest-accepted
